# Generated by Django 5.1.4 on 2025-01-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_category_news_news_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
